import type { IInvoice } from '../interfaces';

const now = Date.now();

export const randomOffset = (): number => {
  const min = 30 * 1000;
  const max = 5 * 60 * 1000;
  return Math.floor(Math.random() * (max - min + 1)) + min;
};

export const originalInvoices: IInvoice[] = [
  {
    id: 'INV001',
    customer: 'Budi',
    eta: 10,
    startTime: new Date(now - randomOffset()),
    tableNumber: 'A1, B2',
    items: [
      { name: 'Nasi Goreng', variant: 'Pedas', qty: 1 },
      { name: 'Mie Ayam', qty: 1 },
    ],
  },
  {
    id: 'INV002',
    customer: 'Sari',
    eta: 15,
    startTime: new Date(now - randomOffset()),
    tableNumber: 'C3',
    items: [
      { name: 'Sate Ayam', variant: 'Tanpa Lemak', qty: 2, notes: 'Tambahkan lontong' },
      { name: 'Soto Betawi', variant: 'Biasa', qty: 1 },
    ],
  },
  {
    id: 'INV003',
    customer: 'Udin',
    eta: 8,
    startTime: new Date(now - randomOffset()),
    tableNumber: 'B1',
    items: [{ name: 'Bakso Urat', variant: 'Super', qty: 1, notes: 'Extra pedas' }],
  },
  {
    id: 'INV004',
    customer: 'Rina',
    eta: 12,
    startTime: new Date(now - randomOffset()),
    tableNumber: 'D4',
    items: [
      { name: 'Ayam Bakar', variant: 'Manis', qty: 1, notes: 'Tanpa lalapan' },
      { name: 'Es Teh Manis', qty: 1 },
      { name: 'Tempe Mendoan', variant: 'Garing', qty: 1 },
    ],
  },
  {
    id: 'INV005',
    customer: 'Anto',
    eta: 5,
    startTime: new Date(now - randomOffset()),
    tableNumber: 'A2',
    items: [
      { name: 'Nasi Kuning', variant: 'Komplit', qty: 1 },
      { name: 'Bakmi Jawa', variant: 'Basah', qty: 1, notes: 'Tanpa kecap' },
      { name: 'Wedang Jahe', qty: 1, notes: 'Kurang manis' },
    ],
  },
  {
    id: 'INV006',
    customer: 'Siti',
    eta: 20,
    startTime: new Date(now - randomOffset()),
    tableNumber: 'F1',
    items: [
      { name: 'Rawon', variant: 'Spesial', qty: 1 },
      { name: 'Perkedel', qty: 2 },
    ],
  },
  {
    id: 'INV007',
    customer: 'Eko',
    eta: 9,
    startTime: new Date(now - randomOffset()),
    tableNumber: 'E3',
    items: [
      { name: 'Lontong Sayur', variant: 'Pedas', qty: 1, notes: 'Tanpa telur' },
      { name: 'Es Campur', qty: 1 },
    ],
  },
  {
    id: 'INV008',
    customer: 'Linda',
    eta: 14,
    startTime: new Date(now - randomOffset()),
    tableNumber: 'B3',
    items: [
      { name: 'Nasi Pecel', qty: 1, notes: 'Tanpa sambal' },
      { name: 'Kerupuk Udang', variant: 'Besar', qty: 1 },
    ],
  },
  {
    id: 'INV009',
    customer: 'Wawan',
    eta: 18,
    startTime: new Date(now - randomOffset()),
    tableNumber: 'C1',
    items: [
      { name: 'Tahu Tek', variant: 'Sedang', qty: 1 },
      { name: 'Es Jeruk', qty: 1, notes: 'Tanpa gula' },
    ],
  },
  {
    id: 'INV010',
    customer: 'Dewi',
    eta: 6,
    startTime: new Date(now - randomOffset()),
    tableNumber: 'A5',
    items: [
      { name: 'Nasi Padang', variant: 'Rendang', qty: 1, notes: 'Tanpa kuah' },
      { name: 'Sayur Nangka', qty: 1 },
      { name: 'Teh Manis Hangat', variant: 'Sedikit Gula', qty: 1 },
      { name: 'Tahu Tek', variant: 'Sedang', qty: 1 },
      { name: 'Nasi Campur Bali', variant: 'Biasa', qty: 1, notes: 'Kurangi sambal matah' },
    ],
  },
  {
    id: 'INV011',
    customer: 'Agus',
    eta: 11,
    startTime: new Date(now - randomOffset()),
    tableNumber: 'B4',
    items: [
      { name: 'Sop Iga', variant: 'Komplit', qty: 1, notes: 'Tanpa bawang goreng' },
      { name: 'Air Putih', qty: 1 },
    ],
  },
  {
    id: 'INV012',
    customer: 'Tini',
    eta: 7,
    startTime: new Date(now - randomOffset()),
    tableNumber: 'G1',
    items: [
      { name: 'Bakwan Jagung', qty: 2 },
      { name: 'Nasi Campur Bali', variant: 'Biasa', qty: 1, notes: 'Kurangi sambal matah' },
    ],
  },
  {
    id: 'INV013',
    customer: 'Yuni',
    eta: 13,
    startTime: new Date(now - randomOffset()),
    tableNumber: 'H2',
    items: [
      { name: 'Gado-Gado', qty: 1, notes: 'Tanpa kerupuk' },
      { name: 'Es Kelapa Muda', qty: 1 },
    ],
  },
  {
    id: 'INV014',
    customer: 'Tono',
    eta: 17,
    startTime: new Date(now - randomOffset()),
    tableNumber: 'F3',
    items: [
      { name: 'Ayam Penyet', variant: 'Ekstra Sambal', qty: 1, notes: 'Pedas maksimal' },
      { name: 'Jus Alpukat', variant: 'Tanpa Cokelat', qty: 1 },
    ],
  },
  {
    id: 'INV015',
    customer: 'Raisa',
    eta: 10,
    startTime: new Date(now - randomOffset()),
    tableNumber: 'G4',
    items: [
      { name: 'Sate Kambing', qty: 1 },
      { name: 'Nasi Putih', qty: 1 },
      { name: 'Teh Pucuk', qty: 1 },
    ],
  },
  {
    id: 'INV016',
    customer: 'Dian',
    eta: 19,
    startTime: new Date(now - randomOffset()),
    tableNumber: 'A3',
    items: [
      { name: 'Nasi Liwet', variant: 'Komplit', qty: 1 },
      { name: 'Telur Dadar', qty: 2, notes: 'Agak gosong' },
    ],
  },
  {
    id: 'INV017',
    customer: 'Bambang',
    eta: 8,
    startTime: new Date(now - randomOffset()),
    tableNumber: 'C5',
    items: [
      { name: 'Ikan Bakar', variant: 'Manis', qty: 1 },
      { name: 'Lalapan', qty: 1 },
      { name: 'Nasi Putih', qty: 1 },
      { name: 'Teh Pucuk', qty: 1 },
    ],
  },
  {
    id: 'INV019',
    customer: 'Sunaryo',
    eta: 8,
    startTime: new Date(now - randomOffset()),
    tableNumber: 'C5',
    items: [
      { name: 'Ikan Bakar', variant: 'Manis', qty: 1 },
      { name: 'Lalapan', qty: 1 },
      { name: 'Nasi Liwet', variant: 'Komplit', qty: 1 },
      { name: 'Telur Dadar', qty: 2, notes: 'Agak gosong' },
      { name: 'Ayam Penyet', variant: 'Ekstra Sambal', qty: 1, notes: 'Pedas maksimal' },
    ],
  },
  {
    id: 'INV018',
    customer: 'Citra',
    eta: 16,
    startTime: new Date(now - randomOffset()),
    tableNumber: 'E2',
    items: [
      { name: 'Soto Ayam', qty: 1, notes: 'Tanpa seledri' },
      { name: 'Kerupuk Bawang', qty: 1 },
      { name: 'Teh Botol', qty: 1, variant: 'Dingin' },
      { name: 'Soto Ayam', qty: 1, notes: 'Tanpa seledri' },
      { name: 'Kerupuk Bawang', qty: 1 },
      { name: 'Teh Botol', qty: 1, variant: 'Dingin' },
      { name: 'Soto Ayam', qty: 1, notes: 'Tanpa seledri' },
      { name: 'Kerupuk Bawang', qty: 1 },
      { name: 'Teh Botol', qty: 1, variant: 'Dingin' },
      { name: 'Soto Ayam', qty: 1, notes: 'Tanpa seledri' },
      { name: 'Kerupuk Bawang', qty: 1 },
      { name: 'Teh Botol', qty: 1, variant: 'Dingin' },
      { name: 'Soto Ayam', qty: 1, notes: 'Tanpa seledri' },
      { name: 'Kerupuk Bawang', qty: 1 },
      { name: 'Teh Botol', qty: 1, variant: 'Dingin' },
      { name: 'Soto Ayam', qty: 1, notes: 'Tanpa seledri' },
      { name: 'Kerupuk Bawang', qty: 1 },
      { name: 'Teh Botol', qty: 1, variant: 'Dingin' },
      { name: 'Kerupuk Bawang', qty: 1 },
      { name: 'Teh Botol', qty: 1, variant: 'Dingin' },
      { name: 'Soto Ayam', qty: 1, notes: 'Tanpa seledri' },
      { name: 'Kerupuk Bawang', qty: 1 },
      { name: 'Teh Botol', qty: 1, variant: 'Dingin' },
      { name: 'Soto Ayam', qty: 1, notes: 'Tanpa seledri' },
      { name: 'Kerupuk Bawang', qty: 1 },
      { name: 'Teh Botol', qty: 1, variant: 'Dingin' },
      { name: 'Soto Ayam', qty: 1, notes: 'Tanpa seledri' },
      { name: 'Kerupuk Bawang', qty: 1 },
      { name: 'Teh Botol', qty: 1, variant: 'Dingin' },
      { name: 'Soto Ayam', qty: 1, notes: 'Tanpa seledri' },
      { name: 'Kerupuk Bawang', qty: 1 },
      { name: 'Teh Botol', qty: 1, variant: 'Dingin' },
      { name: 'Soto Ayam', qty: 1, notes: 'Tanpa seledri' },
      { name: 'Kerupuk Bawang', qty: 1 },
      { name: 'Teh Botol', qty: 1, variant: 'Dingin' },
    ],
  },
  {
    id: 'INV017',
    customer: 'Bambang',
    eta: 8,
    startTime: new Date(now - randomOffset()),
    tableNumber: 'C5',
    items: [{ name: 'Lumpia Basah', variant: 'Agak pedas', qty: 1 }],
  },
];
