// Key Http Requests
export const ACCOUNT_ATTACH_BANK_REQUEST = 'ACCOUNT_ATTACH_BANK_REQUEST';
export const ACCOUNT_USER_BANKS_REQUEST = 'ACCOUNT_USER_BANKS_REQUEST';
export const ACCOUNT_DETAILS_REQUEST = 'ACCOUNT_DETAILS_REQUEST';
export const ACCOUNT_PROFILE_REQUEST = 'ACCOUNT_PROFILE_REQUEST';
export const ACCOUNT_UPDATE_PROFILE_REQUEST = 'ACCOUNT_UPDATE_PROFILE_REQUEST';
export const ACCOUNT_STORE_LIST_REQUEST = 'ACCOUNT_STORE_LIST_REQUEST';
export const ACCOUNT_STORE_LIST_OPERATIONAL_HOURS_REQUEST = 'ACCOUNT_STORE_LIST_OPERATIONAL_HOURS_REQUEST';
export const ACCOUNT_STORE_TABLE_CREATE_REQUEST = 'ACCOUNT_STORE_TABLE_CREATE_REQUEST';
export const ACCOUNT_STORE_TABLE_DELETE_REQUEST = 'ACCOUNT_STORE_TABLE_DELETE_REQUEST';
export const ACCOUNT_STORE_TABLE_DETAIL_REQUEST = 'ACCOUNT_STORE_TABLE_DETAIL_REQUEST';
export const ACCOUNT_STORE_TABLE_LIST_REQUEST = 'ACCOUNT_STORE_TABLE_LIST_REQUEST';
export const ACCOUNT_STORE_TABLE_UPDATE_REQUEST = 'ACCOUNT_STORE_TABLE_UPDATE_REQUEST';

export const ACCOUNT_LIST_COLUMNS_STORE: IColumnDataTable[] = [
  {
    label: 'Store Name',
    translationKey: 'app.store-name',
    sortable: true,
    value: 'name',
  },
  {
    label: 'Address',
    translationKey: 'app.address',
    sortable: true,
    value: 'address',
  },
  {
    label: '',
    sortable: false,
    value: 'action',
    width: '100px',
  },
];
