export const PURCHASE_ORDER_BASE_ENDPOINT = '/purchase-orders';

export const PURCHASE_ORDER_CANCEL_ENDPOINT = `${PURCHASE_ORDER_BASE_ENDPOINT}/{id}/cancel`;
export const PURCHASE_ORDER_CONFIRM_ENDPOINT = `${PURCHASE_ORDER_BASE_ENDPOINT}/{id}/confirm`;
export const PURCHASE_ORDER_SHIP_ENDPOINT = `${PURCHASE_ORDER_BASE_ENDPOINT}/{id}/ship`;
export const PURCHASE_ORDER_RECEIVE_ENDPOINT = `${PURCHASE_ORDER_BASE_ENDPOINT}/{id}/receive`;
export const PURCHASE_ORDER_PAY_ENDPOINT = `${PURCHASE_ORDER_BASE_ENDPOINT}/{id}/pay`;
