export const AUTHENTICATION_BASE_ENDPOINT = '/authentication';
export const AUTHENTICATION_BASE_PERMISSIONS_ENDPOINT = '/permissions/me';
export const AUTHENTICATION_BASE_GOOGLE_ENDPOINT = `${AUTHENTICATION_BASE_ENDPOINT}/google`;
export const AUTHENTICATION_BASE_OTP_ENDPOINT = `${AUTHENTICATION_BASE_ENDPOINT}/otp`;
export const AUTHENTICATION_BASE_STAFF_ENDPOINT = `${AUTHENTICATION_BASE_ENDPOINT}/staff`;

export const AUTHENTICATION_ENDPOINT_GOOGLE_REDIRECT = `${AUTHENTICATION_BASE_GOOGLE_ENDPOINT}/redirect`;
export const AUTHENTICATION_ENDPOINT_PIN = `${AUTHENTICATION_BASE_ENDPOINT}/pin`;
export const AUTHENTICATION_ENDPOINT_PROFILE = `${AUTHENTICATION_BASE_ENDPOINT}/profile`;
export const AUTHENTICATION_ENDPOINT_RESET_PASSWORD = `${AUTHENTICATION_BASE_ENDPOINT}/forgot-password`;
export const AUTHENTICATION_ENDPOINT_SIGN_IN = `${AUTHENTICATION_BASE_ENDPOINT}/login`;
export const AUTHENTICATION_ENDPOINT_SIGN_UP = `${AUTHENTICATION_BASE_ENDPOINT}/register`;
export const AUTHENTICATION_ENDPOINT_SEND_OTP = `${AUTHENTICATION_BASE_OTP_ENDPOINT}/generate`;
export const AUTHENTICATION_ENDPOINT_STAFF_LOGIN = `${AUTHENTICATION_BASE_STAFF_ENDPOINT}/login`;
export const AUTHENTICATION_ENDPOINT_STAFF_LOGOUT = `${AUTHENTICATION_BASE_STAFF_ENDPOINT}/logout`;
export const AUTHENTICATION_ENDPOINT_VERIFY_OTP = `${AUTHENTICATION_BASE_OTP_ENDPOINT}/verify`;
