export const AUTHENTICATION_TITLE = 'Authentication';

export const AUTHENTICATION_LOGIN_REQUEST = 'AUTHENTICATION_LOGIN_REQUEST';
export const AUTHENTICATION_RESET_PASSWORD_REQUEST = 'AUTHENTICATION_RESET_PASSWORD_REQUEST';
