export const AUTHENTICATION_TITLE = 'Authentication';

// Key Http Request
export const AUTHENTICATION_CONNECT_DEVICE_REQUEST = 'AUTHENTICATION_CONNECT_DEVICE_REQUEST';
export const AUTHENTICATION_CREATE_NEW_PASSWORD_REQUEST = 'AUTHENTICATION_CREATE_NEW_PASSWORD_REQUEST';
export const AUTHENTICATION_GOOGLE_REDIRECT_REQUEST = 'AUTHENTICATION_GOOGLE_REDIRECT_REQUEST';
export const AUTHENTICATION_PERMISSIONS_REQUEST = 'AUTHENTICATION_PERMISSIONS_REQUEST';
export const AUTHENTICATION_PROFILE_REQUEST = 'AUTHENTICATION_PROFILE_REQUEST';
export const AUTHENTICATION_SEND_OTP_REQUEST = 'AUTHENTICATION_SEND_OTP_REQUEST';
export const AUTHENTICATION_SIGN_IN_REQUEST = 'AUTHENTICATION_SIGN_IN_REQUEST';
export const AUTHENTICATION_SIGN_UP_REQUEST = 'AUTHENTICATION_SIGN_UP_REQUEST';
export const AUTHENTICATION_VERIFY_OTP_REQUEST = 'AUTHENTICATION_VERIFY_OTP_REQUEST';
export const AUTHENTICATION_RESET_PASSWORD_REQUEST = 'AUTHENTICATION_RESET_PASSWORD_REQUEST';
export const AUTHENTICATION_RESEND_RESET_PASSWORD_REQUEST = 'AUTHENTICATION_RESEND_RESET_PASSWORD_REQUEST';
