export const AUTHENTICATION_BASE_ENDPOINT = '/authentication';
export const AUTHENTICATION_BASE_OTP_ENDPOINT = `${AUTHENTICATION_BASE_ENDPOINT}/otp`;

export const AUTHENTICATION_ENDPOINT_SIGN_IN = `${AUTHENTICATION_BASE_ENDPOINT}/login`;
export const AUTHENTICATION_ENDPOINT_SIGN_UP = `${AUTHENTICATION_BASE_ENDPOINT}/register`;
export const AUTHENTICATION_ENDPOINT_RESET_PASSWORD = `${AUTHENTICATION_BASE_ENDPOINT}/forgot-password`;
export const AUTHENTICATION_ENDPOINT_SEND_OTP = `${AUTHENTICATION_BASE_OTP_ENDPOINT}/generate`;
export const AUTHENTICATION_ENDPOINT_VERIFY_OTP = `${AUTHENTICATION_BASE_OTP_ENDPOINT}/verify`;
