export const SETTING_LIST_CHARGES_REQUEST = 'SETTING_LIST_CHARGES_REQUEST';
export const SETTING_INVOICE_DETAIL_REQUEST = 'SETTING_INVOICE_DETAIL_REQUEST';
export const SETTING_UPDATE_CHARGES_REQUEST = 'SETTING_UPDATE_CHARGES_REQUEST';
export const SETTING_UPDATE_INVOICE_REQUEST = 'SETTING_UPDATE_INVOICE_REQUEST';
