// Endpoints
export const WASTE_LOG_BASE_ENDPOINT = '/waste-log';

// Key Http Request
export const WASTE_LOG_BATCH_LIST_REQUEST = 'WASTE_LOG_BATCH_LIST_REQUEST';
export const WASTE_LOG_CREATE_REQUEST = 'WASTE_LOG_CREATE_REQUEST';
export const WASTE_LOG_DELETE_REQUEST = 'WASTE_LOG_DELETE_REQUEST';
export const WASTE_LOG_DETAIL_REQUEST = 'WASTE_LOG_DETAIL_REQUEST';
export const WASTE_LOG_LIST_REQUEST = 'WASTE_LOG_LIST_REQUEST';
export const WASTE_LOG_UPDATE_REQUEST = 'WASTE_LOG_UPDATE_REQUEST';
