export const SALES_ORDER_CASH_DRAWER_BASE_ENDPOINT = '/cash-drawer';
export const SALES_ORDER_INVOICE_BASE_ENDPOINT = '/invoice';

// Cash Drawer
export const SALES_ORDER_CASH_DRAWER_ADD_TRANSACTION_ENDPOINT = `${SALES_ORDER_CASH_DRAWER_BASE_ENDPOINT}/transaction/add`;
export const SALES_ORDER_CASH_DRAWER_CLOSE_ENDPOINT = `${SALES_ORDER_CASH_DRAWER_BASE_ENDPOINT}/close`;
export const SALES_ORDER_CASH_DRAWER_EDIT_ENDPOINT = `${SALES_ORDER_CASH_DRAWER_BASE_ENDPOINT}/edit`;
export const SALES_ORDER_CASH_DRAWER_LIST_ENDPOINT = `${SALES_ORDER_CASH_DRAWER_BASE_ENDPOINT}/list`;
export const SALES_ORDER_CASH_DRAWER_OPEN_ENDPOINT = `${SALES_ORDER_CASH_DRAWER_BASE_ENDPOINT}/open`;
export const SALES_ORDER_CASH_DRAWER_STATUS_ENDPOINT = `${SALES_ORDER_CASH_DRAWER_BASE_ENDPOINT}/status`;
export const SALES_ORDER_CASH_DRAWER_TRANSACTION_ENDPOINT = `${SALES_ORDER_CASH_DRAWER_BASE_ENDPOINT}/transactions`;
