export const CASH_DRAWER_BASE_ENDPOINT = '/cash-drawer';

export const CASH_DRAWER_ADD_TRANSACTION_ENDPOINT = `${CASH_DRAWER_BASE_ENDPOINT}/transaction/add`;
export const CASH_DRAWER_CLOSE_ENDPOINT = `${CASH_DRAWER_BASE_ENDPOINT}/close`;
export const CASH_DRAWER_DETAILS_ENDPOINT = `${CASH_DRAWER_BASE_ENDPOINT}/details`;
export const CASH_DRAWER_EDIT_ENDPOINT = `${CASH_DRAWER_BASE_ENDPOINT}/edit`;
export const CASH_DRAWER_LIST_ENDPOINT = `${CASH_DRAWER_BASE_ENDPOINT}/list`;
export const CASH_DRAWER_OPEN_ENDPOINT = `${CASH_DRAWER_BASE_ENDPOINT}/open`;
export const CASH_DRAWER_STATUS_ENDPOINT = `${CASH_DRAWER_BASE_ENDPOINT}/status`;
export const CASH_DRAWER_TRANSACTION_ENDPOINT = `${CASH_DRAWER_BASE_ENDPOINT}/transactions`;
