// API endpoint object
export const TRANSFER_STOCK_API = {
  CHANGE_STATUS: '/transfer-stock/transfer/change-status',
  CREATE: '/transfer-stock/transfer',
  DELETE: '/transfer-stock/transfer/delete',
  DETAIL: '/transfer-stock/detail',
  LIST: '/transfer-stock/transfer',
  UPDATE: '/transfer-stock/transfer',
};

// Key Http Request (for tracking)
export const TRANSFER_STOCK_APPROVE_REQUEST = 'TRANSFER_STOCK_APPROVE_REQUEST';
export const TRANSFER_STOCK_CANCEL_REQUEST = 'TRANSFER_STOCK_CANCEL_REQUEST';
export const TRANSFER_STOCK_CREATE_REQUEST = 'TRANSFER_STOCK_CREATE_REQUEST';
export const TRANSFER_STOCK_DELETE_REQUEST = 'TRANSFER_STOCK_DELETE_REQUEST';
export const TRANSFER_STOCK_DETAILS_REQUEST = 'TRANSFER_STOCK_DETAILS_REQUEST';
export const TRANSFER_STOCK_LIST_REQUEST = 'TRANSFER_STOCK_LIST_REQUEST';
export const TRANSFER_STOCK_RECEIVE_REQUEST = 'TRANSFER_STOCK_RECEIVE_REQUEST';
export const TRANSFER_STOCK_REJECT_REQUEST = 'TRANSFER_STOCK_REJECT_REQUEST';
export const TRANSFER_STOCK_SHIP_REQUEST = 'TRANSFER_STOCK_SHIP_REQUEST';
export const TRANSFER_STOCK_UPDATE_REQUEST = 'TRANSFER_STOCK_UPDATE_REQUEST';
