export const CASHIER_BASE_PAYMENT_ENDPOINT = '/payment';

export const CASHIER_ENDPOINT_PRODUCTS = `/products`;
export const CASHIER_ENDPOINT_CATEGORIES = `/categories`;

export const CASHIER_ENDPOINT_PAYMENT_PROCESS = `${CASHIER_BASE_PAYMENT_ENDPOINT}/process`;
export const CASHIER_ENDPOINT_PAYMENT_CALCULATE_ESTIMATION = `${CASHIER_BASE_PAYMENT_ENDPOINT}/calculate/estimation`;
export const CASHIER_ENDPOINT_PAYMENT_METHOD = `${CASHIER_BASE_PAYMENT_ENDPOINT}/method`;
