export const CASHIER_BASE_INVOICE_ENDPOINT = '/invoice';
export const CASHIER_BASE_PROCESS_ENDPOINT = '/process';

export const CASHIER_BASE_PAYMENT_ENDPOINT = '/payment';

export const CASHIER_ENDPOINT_PRODUCTS = `/products`;
export const CASHIER_ENDPOINT_PRODUCTS_BARCODE = `/products/barcode`;
export const CASHIER_ENDPOINT_CATEGORIES = `/categories/all`;
export const CASHIER_ENDPOINT_CATEGORIES_PRODUCT = `/categories/products`;
export const CASHIER_ENDPOINT_COSTUMERS = `/customers`;

export const CASHIER_ENDPOINT_PAYMENT_UNPAID = `${CASHIER_BASE_INVOICE_ENDPOINT + CASHIER_BASE_PROCESS_ENDPOINT}/payment`;

export const CASHIER_ENDPOINT_PAYMENT_INSTANT = `${CASHIER_BASE_INVOICE_ENDPOINT + CASHIER_BASE_PROCESS_ENDPOINT}/instant`;

export const CASHIER_ENDPOINT_PAYMENT_PROCESS = `${CASHIER_BASE_INVOICE_ENDPOINT + CASHIER_BASE_PROCESS_ENDPOINT}/checkout`;

export const CASHIER_ENDPOINT_PAYMENT_CALCULATE_ESTIMATION = `${CASHIER_BASE_INVOICE_ENDPOINT}/calculate/estimation`;

export const CASHIER_ENDPOINT_PAYMENT_METHOD = `${CASHIER_BASE_PAYMENT_ENDPOINT}/method`;

export const CASHIER_ENDPOINT_SIMULATE_PAYMENT = `/invoice/webhook/core/qris`;
