export const CASHIER_ORDER_TYPE = [
  {
    code: 'dine_in',
    label: 'Dine In',
    available: true,
  },
  {
    code: 'take_away',
    label: 'Take Away',
    available: true,
  },
  {
    code: 'self_order',
    label: 'Self Order',
    available: true,
  },
];

export const CASHIER_PROVIDER = 'midtrans';

export const CASHIER_DUMMY_LIST_FLOOR = [
  {
    value: '1',
    label: 'Floor 1',
    available: true,
  },
  {
    value: '2',
    label: 'Floor 2',
    available: false,
  },
  {
    value: '3',
    label: 'Floor 3',
    available: true,
  },
  {
    value: '4',
    label: 'Floor 4',
    available: false,
  },
];

export const CASHIER_DUMMY_LIST_TABLE = [
  {
    value: '1',
    label: 'Table 1',
    available: true,
    totalSeat: 4,
    floor: 1,
    statusTable: 'available',
  },
  {
    value: '2',
    label: 'Table 2',
    available: false,
    totalSeat: 8,
    floor: 1,
    statusTable: 'available',
  },
  {
    value: '3',
    label: 'Table 3',
    available: true,
    totalSeat: 12,
    floor: 1,
    statusTable: 'available',
  },
  {
    value: '4',
    label: 'Table 4',
    available: false,
    totalSeat: 6,
    floor: 1,
    statusTable: 'available',
  },
  {
    value: '5',
    label: 'Table 5',
    available: false,
    totalSeat: 6,
    floor: 1,
    statusTable: 'available',
  },
  {
    value: '6',
    label: 'Table 6',
    available: false,
    totalSeat: 6,
    floor: 2,
    statusTable: 'available',
  },
  {
    value: '7',
    label: 'Table 7',
    available: false,
    totalSeat: 6,
    floor: 2,
    statusTable: 'available',
  },
  {
    value: '8',
    label: 'Table 8',
    available: false,
    totalSeat: 6,
    floor: 2,
    statusTable: 'available',
  },
  {
    value: '9',
    label: 'Table 9',
    available: false,
    totalSeat: 6,
    floor: 2,
    statusTable: 'available',
  },
  {
    value: '10',
    label: 'Table 10',
    available: false,
    totalSeat: 12,
    floor: 2,
    statusTable: 'available',
  },
  {
    value: '11',
    label: 'Table 11',
    available: false,
    totalSeat: 2,
    floor: 2,
    statusTable: 'available',
  },
  {
    value: '12',
    label: 'Table 12',
    available: false,
    totalSeat: 2,
    floor: 2,
    statusTable: 'available',
  },
  {
    value: '13',
    label: 'Table 13',
    available: false,
    totalSeat: 2,
    floor: 2,
    statusTable: 'available',
  },
  {
    value: '14',
    label: 'Table 14',
    available: false,
    totalSeat: 2,
    floor: 2,
    statusTable: 'available',
  },
  {
    value: '15',
    label: 'Table 15',
    available: false,
    totalSeat: 2,
    floor: 2,
    statusTable: 'available',
  },
  {
    value: '16',
    label: 'Table 16',
    available: false,
    totalSeat: 2,
    floor: 2,
    statusTable: 'available',
  },
];

export const CASHIER_DUMMY_VOUCHER = [
  {
    code: '1',
    label: 'Voucher A',
    available: true,
    minPurchase: 50000,
    maxDiscount: 10000,
    discount: 10000,
    validFrom: '31 July 2024',
    validUntil: '31 July 2025',
    type: 'percentage',
    stock: 10,
  },
  {
    code: '2',
    label: 'Voucher B',
    available: false,
    minPurchase: 50000,
    maxDiscount: 10000,
    discount: 10000,
    validFrom: '31 July 2024',
    validUntil: '31 July 2025',
    type: 'nominal',
    stock: 10,
  },
  {
    code: '3',
    label: 'Voucher C',
    available: true,
    minPurchase: 50000,
    maxDiscount: 10000,
    discount: 10000,
    validFrom: '31 July 2024',
    validUntil: '31 July 2025',
    type: 'percentage',
    stock: 10,
  },
];

export const CASHIER_DUMMY_PARAMS_SIMULATE_PAYMENT = {
  acquirer: 'gopay',
  currency: 'IDR',
  expiry_time: '2025-05-15 13:43:44',
  fraud_status: 'accept',
  gross_amount: '50000',
  issuer: 'gopay',
  merchant_id: 'G670501757',
  order_id: 'invoiceId',
  payment_type: 'qris',
  settlement_time: '2025-05-15 13:43:44',
  signature_key: 'asf4a68svca6v3zv6av',
  status_code: '200',
  status_message: 'midtrans payment notification',
  transaction_id: '318db42f-c746-4adb-8337-3b505db445fe',
  transaction_status: 'settlement',
  transaction_time: '2025-05-15 13:43:44',
  transaction_type: 'on-US',
};

export const CASHIER_DUMMY_LIST_CATEGORY = [
  {
    id: 1,
    name: 'Food',
    total: 120,
    image: 'https://foodish-api.com/images/pasta/pasta10.jpg',
  },
  {
    id: 2,
    name: 'Beverage',
    total: 120,
    image: 'https://foodish-api.com/images/pizza/pizza10.jpg',
  },
  {
    id: 3,
    name: 'Pastry',
    total: 120,
    image: 'https://foodish-api.com/images/samosa/samosa10.jpg',
  },
  {
    id: 4,
    name: 'Drinks',
    total: 120,
    image: 'https://foodish-api.com/images/burger/burger10.jpg',
  },
  {
    id: 5,
    name: 'Pasta',
    total: 120,
    image: 'https://foodish-api.com/images/butter-chicken/butter-chicken10.jpg',
  },
  {
    id: 6,
    name: 'Pizza',
    total: 120,
    image: 'https://foodish-api.com/images/pizza/pizza10.jpg',
  },
  {
    id: 7,
    name: 'Burger',
    total: 120,
    image: 'https://foodish-api.com/images/burger/burger10.jpg',
  },
  {
    id: 8,
    name: 'Butter Chicken',
    total: 120,
    image: 'https://foodish-api.com/images/butter-chicken/butter-chicken10.jpg',
  },
  {
    id: 1,
    name: 'Food',
    total: 120,
    image: 'https://foodish-api.com/images/pasta/pasta10.jpg',
  },
  {
    id: 2,
    name: 'Beverage',
    total: 120,
    image: 'https://foodish-api.com/images/pizza/pizza10.jpg',
  },
  {
    id: 3,
    name: 'Pastry',
    total: 120,
    image: 'https://foodish-api.com/images/samosa/samosa10.jpg',
  },
  {
    id: 4,
    name: 'Drinks',
    total: 120,
    image: 'https://foodish-api.com/images/burger/burger10.jpg',
  },
  {
    id: 5,
    name: 'Pasta',
    total: 120,
    image: 'https://foodish-api.com/images/butter-chicken/butter-chicken10.jpg',
  },
  {
    id: 6,
    name: 'Pizza',
    total: 120,
    image: 'https://foodish-api.com/images/pizza/pizza10.jpg',
  },
  {
    id: 7,
    name: 'Burger',
    total: 120,
    image: 'https://foodish-api.com/images/burger/burger10.jpg',
  },
  {
    id: 8,
    name: 'Butter Chicken',
    total: 120,
    image: 'https://foodish-api.com/images/butter-chicken/butter-chicken10.jpg',
  },
];

export const CASHIER_DUMMY_LIST_FEATURED_PRODUCT = [
  {
    productId: '1',
    name: 'Creamy Pasta',
    category: 'Food',
    quantity: 44,
    price: '10990',
    discountedPrice: null,
    image: 'https://foodish-api.com/images/pasta/pasta6.jpg',
    variant: [
      { variantId: '1', name: 'No adds on', price: 0 },
      { variantId: '2', name: 'With parmesan sauce', price: 5000 },
      { variantId: '3', name: 'Extra cheese', price: 3000 },
      { variantId: '4', name: 'Add grilled chicken', price: 7000 },
    ],
  },
  {
    productId: '2',
    name: 'Cheese Pasta',
    category: 'Food',
    quantity: 44,
    price: '15990',
    discountedPrice: null,
    image: 'https://foodish-api.com/images/pasta/pasta2.jpg',
    variant: [
      { variantId: '1', name: 'Regular', price: 0 },
      { variantId: '2', name: 'Extra cheese', price: 4000 },
      { variantId: '3', name: 'With truffle oil', price: 8000 },
    ],
  },
  {
    productId: '3',
    name: 'Pepperoni Pizza',
    category: 'Food',
    quantity: 44,
    price: '15990',
    discountedPrice: '14990',
    image: 'https://foodish-api.com/images/pizza/pizza2.jpg',
    variant: [
      { variantId: '1', name: 'Regular size', price: 0 },
      { variantId: '2', name: 'Large size', price: 10000 },
      { variantId: '3', name: 'Extra pepperoni', price: 5000 },
    ],
  },
  {
    productId: '4',
    name: 'Margarita Pizza',
    category: 'Food',
    quantity: 44,
    price: '20990',
    discountedPrice: '19990',
    image: 'https://foodish-api.com/images/pizza/pizza5.jpg',
    variant: [
      { variantId: '1', name: 'Regular size', price: 0 },
      { variantId: '2', name: 'Large size', price: 10000 },
      { variantId: '3', name: 'Extra mozzarella', price: 6000 },
    ],
  },
  {
    productId: '5',
    name: 'Classic Cheeseburger',
    category: 'Food',
    quantity: 44,
    price: '20990',
    discountedPrice: '19990',
    image: 'https://foodish-api.com/images/burger/burger5.jpg',
    variant: [
      { variantId: '1', name: 'Single patty', price: 0 },
      { variantId: '2', name: 'Double patty', price: 8000 },
      { variantId: '3', name: 'Add bacon', price: 5000 },
    ],
  },
  {
    productId: '6',
    name: 'Butter Chicken',
    category: 'Food',
    quantity: 44,
    price: '20990',
    discountedPrice: '19990',
    image: 'https://foodish-api.com/images/butter-chicken/butter-chicken5.jpg',
    variant: [
      { variantId: '1', name: 'Mild spice', price: 0 },
      { variantId: '2', name: 'Medium spice', price: 2000 },
      { variantId: '3', name: 'Extra spicy', price: 4000 },
      { variantId: '4', name: 'With garlic naan', price: 5000 },
    ],
  },
];

export const CASHIER_DUMMY_LIST_FOOD = [
  {
    productId: '7',
    name: 'Classic Pasta',
    category: 'Food',
    quantity: 44,
    price: '10990',
    discountedPrice: '9990',
    image: 'https://foodish-api.com/images/pasta/pasta1.jpg',
    variant: [
      { variantId: '1', name: 'Regular', price: 0 },
      { variantId: '2', name: 'Extra cheese', price: 3000 },
      { variantId: '3', name: 'Add grilled chicken', price: 5000 },
    ],
  },
  {
    productId: '8',
    name: 'Cheese Pasta',
    category: 'Food',
    quantity: 44,
    price: '15990',
    discountedPrice: '14990',
    image: 'https://foodish-api.com/images/pasta/pasta2.jpg',
    variant: [
      { variantId: '1', name: 'Regular', price: 0 },
      { variantId: '2', name: 'Double cheese', price: 4000 },
      { variantId: '3', name: 'With truffle oil', price: 7000 },
    ],
  },
];

export const CASHIER_DUMMY_LIST_DRINK = [
  {
    productId: '13',
    name: 'Samosa Snack',
    category: 'Beverage',
    quantity: 44,
    price: '5990',
    discountedPrice: '4990',
    image: 'https://foodish-api.com/images/samosa/samosa1.jpg',
    variant: [{ variantId: '1', name: 'Regular', price: 0 }],
  },
];
