/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBaseFormGroup: typeof import('@components/base/AppBaseFormGroup.vue')['default']
    AppBaseSvg: typeof import('@components/base/AppBaseSvg.vue')['default']
    AppBaseToast: typeof import('@components/base/AppBaseToast.vue')['default']
    PrimeVueAvatar: typeof import('primevue/avatar')['default']
    PrimeVueBreadcrumb: typeof import('primevue/breadcrumb')['default']
    PrimeVueButton: typeof import('primevue/button')['default']
    PrimeVueCard: typeof import('primevue/card')['default']
    PrimeVueCheckbox: typeof import('primevue/checkbox')['default']
    PrimeVueDivider: typeof import('primevue/divider')['default']
    PrimeVueDrawer: typeof import('primevue/drawer')['default']
    PrimeVueIconField: typeof import('primevue/iconfield')['default']
    PrimeVueInputIcon: typeof import('primevue/inputicon')['default']
    PrimeVueInputOtp: typeof import('primevue/inputotp')['default']
    PrimeVueInputText: typeof import('primevue/inputtext')['default']
    PrimeVueMultiSelect: typeof import('primevue/multiselect')['default']
    PrimeVuePassword: typeof import('primevue/password')['default']
    PrimeVueSelect: typeof import('primevue/select')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
