/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBaseSvg: typeof import('@components/base/AppBaseSvg.vue')['default']
    AppBaseToast: typeof import('@components/base/AppBaseToast.vue')['default']
    PrimeVueAvatar: typeof import('primevue/avatar')['default']
    PrimeVueBreadcrumb: typeof import('primevue/breadcrumb')['default']
    PrimeVueButton: typeof import('primevue/button')['default']
    PrimeVueCheckbox: typeof import('primevue/checkbox')['default']
    PrimeVueDivider: typeof import('primevue/divider')['default']
    PrimeVueDropdown: typeof import('primevue/dropdown')['default']
    PrimeVueIconField: typeof import('primevue/iconfield')['default']
    PrimeVueInputIcon: typeof import('primevue/inputicon')['default']
    PrimeVueInputNumber: typeof import('primevue/inputnumber')['default']
    PrimeVueInputText: typeof import('primevue/inputtext')['default']
    PrimeVueMultiSelect: typeof import('primevue/multiselect')['default']
    PrimeVueSelect: typeof import('primevue/select')['default']
    PrimeVueToggleSwitch: typeof import('primevue/toggleswitch')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
