/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBaseSvg: typeof import('@components/base/AppBaseSvg.vue')['default']
    AppBaseToast: typeof import('@components/base/AppBaseToast.vue')['default']
    PrimeVueAvatar: typeof import('primevue/avatar')['default']
    PrimeVueBreadcrumb: typeof import('primevue/breadcrumb')['default']
    PrimeVueButton: typeof import('primevue/button')['default']
    PrimeVueChart: typeof import('primevue/chart')['default']
    PrimeVueChip: typeof import('primevue/chip')['default']
    PrimeVueColumn: typeof import('primevue/column')['default']
    PrimeVueDataTable: typeof import('primevue/datatable')['default']
    PrimeVueDatePicker: typeof import('primevue/datepicker')['default']
    PrimeVueDialog: typeof import('primevue/dialog')['default']
    PrimeVueDivider: typeof import('primevue/divider')['default']
    PrimeVueIconField: typeof import('primevue/iconfield')['default']
    PrimeVueInputIcon: typeof import('primevue/inputicon')['default']
    PrimeVueInputText: typeof import('primevue/inputtext')['default']
    PrimeVueMeterGroup: typeof import('primevue/metergroup')['default']
    PrimeVuePopover: typeof import('primevue/popover')['default']
    PrimeVueTextarea: typeof import('primevue/textarea')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
